com.mindsmiths.telegramAdapter.events.TelegramReceivedMessage:
  - !GetOrCreateAgentByConnection
    connectionName: telegram
    connectionField: chatId
    agentType: agents.PlayerAgent
com.mindsmiths.telegramAdapter.events.TelegramKeyboardAnswered:
  - !GetOrCreateAgentByConnection
    connectionName: telegram
    connectionField: chatId
    agentType: agents.PlayerAgent