global:
  dependencies:
    python:
      - forge-sdk==4.0.0a7
      - forge-cli==4.0.0a7
      - cecs==4.0.0a1
      - services/*.py
  env:
    PROJECT_NAME: "Nola"
    PROJECT_SLUG: "nola"

    LOG_LEVEL: INFO
  
  secrets:
    FOO: bar

  repository: "nexus.vingd.net"

services:
  rule-engine:
    type: java
    resources:
      cpu: 500m
      memory: 650Mi

  heartbeat-scheduler:
    package: heartbeat
    type: python
    version: 4.0.0a4
    env:
      HEARTBEAT_CYCLE: 5
    db:
      mongo: true
    resources:
      cpu: 69m
      memory: 65Mi

  heartbeat-sender:
    package: heartbeat
    type: python
    version: 4.0.0a4
    db:
      mongo: true
    resources:
      cpu: 84m
      memory: 94Mi

  telegram-adapter:
    type: python
    version: 4.0.0a9
    db:
      mongo: true
    env:
      TELEGRAM_BOT_TOKEN: "{{ env.TELEGRAM_BOT_TOKEN }}"
    resources:
      cpu: 81m
      memory: 130Mi

  gpt3-adapter:
    type: python
    version: 4.0.0a7
    env:
      OPENAI_API_KEY: "{{ env.OPENAI_API_KEY }}"
    resources:
      cpu: 81m
      memory: 130Mi
