com.mindsmiths.armory.event.UserConnected:
  - !GetOrCreateAgentByConnection
    connectionName: armory
    connectionField: connectionId
    agentType: agents.Felix
com.mindsmiths.armory.event.Submit:
  - !GetOrCreateAgentByConnection
    connectionName: armory
    connectionField: connectionId
    agentType: agents.Felix
com.mindsmiths.armory.event.UserDisconnected:
  - !GetOrCreateAgentByConnection
    connectionName: armory
    connectionField: connectionId
    agentType: agents.Felix
