package rules.gameAdmin;

import com.mindsmiths.ruleEngine.util.Log
import com.mindsmiths.sdk.utils.Utils

import agents.GameAdmin
import models.Celebrity
import models.EvaluationResult
import signals.*


// *** Game management ***
rule "New game request"
    when
        signal: NewGameRequest() from entry-point "signals"
        agent: GameAdmin()
    then
        Celebrity celebrity = Utils.randomChoice(agent.getCelebrities());
        agent.send(signal.getFrom(), new StartGame(celebrity));
        delete(signal);
end
