package rules.gameAdmin;

import com.mindsmiths.ruleEngine.util.Log

import agents.GameAdmin
import models.Celebrity
import models.EvaluationResult
import signals.*


// *** Player management ***
rule "New player joined"
    when
        signal: PlayerJoined(player: player) from entry-point "signals"
        agent: GameAdmin()
    then
        modify(agent) {
            getPlayers().add(player)
        };
        Log.info("New player joined! Welcome, " + player.getName() + "!");
        Log.info("There are now " + agent.getPlayers().size() + " players in the game.");
        delete(signal);
end

// *** Celebrity management ***
rule "New celebrity"
    when
        celebrity: Celebrity() from entry-point "signals"
        agent: GameAdmin()
    then
        agent.getCelebrities().add(celebrity);
        delete(celebrity);
end
