global:
  dependencies:
    python:
      - forge-sdk==4.0.0a9
      - forge-cli==4.0.0a8
      - cecs==4.0.0a1
      - psutil==5.9.1
      - services/*.py
  env:
    PROJECT_SLUG: "orchestration"

    LOG_LEVEL: INFO

  repository: "nexus.vingd.net"

  cecs:
    params: "-e venv"

services:
  rule-engine:
    type: java
    resources:
      cpu: 500m
      memory: 650Mi

  heartbeat-scheduler:
    package: heartbeat
    type: python
    version: 4.0.0a4
    env:
      HEARTBEAT_CYCLE: 1
    db:
      mongo: true
    dependencies:
      - rule-engine-api==4.0.0a20
    resources:
      cpu: 69m
      memory: 65Mi

  heartbeat-sender:
    package: heartbeat
    type: python
    version: 4.0.0a4
    db:
      mongo: true
    dependencies:
      - rule-engine-api==4.0.0a20
    resources:
      cpu: 84m
      memory: 94Mi

  telegram-adapter:
    type: python
    version: 4.0.0a9
    db:
      mongo: true
    env:
      TELEGRAM_BOT_TOKEN: "{{env.TELEGRAM_BOT_TOKEN}}"
    resources:
      cpu: 81m
      memory: 130Mi

  forge-api:
    type: python
    version: 4.0.0a2
    command:
      run: "uvicorn forge_api.service:app"
      cwd: "."
    resources:
      cpu: 81m
      memory: 130Mi

  websocket-adapter:
    type: python
    db:
      mongo: true
    dependencies:
      - rule-engine-api==4.0.0a20
      - websockets==10.3
    exposed: true
    resources:
      cpu: 100m
      memory: 100Mi
