package rules.smith;

import com.mindsmiths.ruleEngine.model.Heartbeat
import com.mindsmiths.ruleEngine.util.Log

import agents.smith.Smith


rule "Smith's Heartbeat"
    when
        Heartbeat() from entry-point "signals"
    then
        Integer doctors = Smith.countAgents("Doctor");
        Integer patients = Smith.countAgents("Patient") + Smith.countAgents("RoboPatient");

        Log.info(
            "Smith's heartbeat - "
            + "num doctors: " + doctors
            + ", num patients: " + patients
        );
end
